package com.asraf.rsrc.entities;
// Generated Jul 29, 2019 12:51:18 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * StudentProfile generated by hbm2java
 */
@Entity
@Table(name = "student_profile")
public class StudentProfile extends BaseEntity implements java.io.Serializable {

	private Long id;
	private Student student;
	private String address;
	private String phoneNumber;

	public StudentProfile() {
	}

	public StudentProfile(Student student, String address, String phoneNumber) {
		this.student = student;
		this.address = address;
		this.phoneNumber = phoneNumber;
	}

	@GenericGenerator(name = "com.asraf.entities.StudentProfileIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "student"))
	@Id
	@GeneratedValue(generator = "com.asraf.entities.StudentProfileIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_number", nullable = false, length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}
