package com.asraf.rsrc.entities;
// Generated Jul 29, 2019 12:51:18 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student")
public class Student extends BaseEntity implements java.io.Serializable {

	private Long id;
	private String email;
	private String name;
	private StudentProfile studentProfile;
	private Set<StudentVerification> studentVerifications = new HashSet<StudentVerification>(0);

	public Student() {
	}

	public Student(String email, String name) {
		this.email = email;
		this.name = name;
	}

	public Student(String email, String name, StudentProfile studentProfile,
			Set<StudentVerification> studentVerifications) {
		this.email = email;
		this.name = name;
		this.studentProfile = studentProfile;
		this.studentVerifications = studentVerifications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "student")
	public StudentProfile getStudentProfile() {
		return this.studentProfile;
	}

	public void setStudentProfile(StudentProfile studentProfile) {
		this.studentProfile = studentProfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<StudentVerification> getStudentVerifications() {
		return this.studentVerifications;
	}

	public void setStudentVerifications(Set<StudentVerification> studentVerifications) {
		this.studentVerifications = studentVerifications;
	}

}
